// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimationCharacters.Migrations
{
    [DbContext(typeof(AnimationCharactersContext))]
    partial class AnimationCharactersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimationCharacters.Models.AnimationCharacter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Age")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scenery")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleMovie")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("AnimationCharacter");
                });
#pragma warning restore 612, 618
        }
    }
}
